version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3050:80"
    depends_on:
      - client
      - api


  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=4000
      - NODE_ENV=development
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres


  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      # - PORT=3000
      - NODE_ENV=development
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app
      - /app/node_modules
    # depends_on:
    #   - api


  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./server/.env.development
  