FROM node:18-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .

COPY ./src/database/schema.prisma ./src/database/schema.prisma

RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]

